name: API Testing Workflow

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can adjust the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run API tests
        run: |
          export key="d7aab2d7"
          export youtubeApiKey="AIzaSyD3Uzv6UDRQsPlCf4B9oO7C3TVsXs1dClM"
          node index.js

