name: My API Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      key: ${{ secrets.key }}
      youtubeApiKey: ${{ secrets.youtubeApiKey }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy
        run: |
          # You can access the environment variables directly here
          echo "API Key: $key"
          echo "YouTube API Key: $youtubeApiKey"

          # Use your environment variables as needed in your Node.js script
          node index.js
